// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_github_search_rx_redux/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i7;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i13;

import 'package:built_collection/built_collection.dart' as _i12;
import 'package:cancellation_token_hoc081098/cancellation_token_hoc081098.dart'
    as _i6;
import 'package:flutter_github_search_rx_redux/data/remote/color_remote_source.dart'
    as _i11;
import 'package:flutter_github_search_rx_redux/data/remote/search_remote_source.dart'
    as _i9;
import 'package:flutter_github_search_rx_redux/data/remote/search_result.dart'
    as _i10;
import 'package:http/http.dart' as _i2;
import 'package:http_client_hoc081098/src/interface.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart_ext/single.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSingle_1<T> extends _i1.SmartFake implements _i3.Single<T> {
  _FakeSingle_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SimpleHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.SimpleHttpClient {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> send(
    _i2.BaseRequest? request, {
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
          {#cancelToken: cancelToken},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #send,
            [request],
            {#cancelToken: cancelToken},
          ),
        )),
      ) as _i5.Future<_i2.Response>);
  @override
  _i5.Future<dynamic> getJson(
    Uri? url, {
    Map<String, String>? headers,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJson,
          [url],
          {
            #headers: headers,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> postMultipart(
    Uri? url,
    List<_i2.MultipartFile>? files, {
    Map<String, String>? headers,
    Map<String, String>? fields,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postMultipart,
          [
            url,
            files,
          ],
          {
            #headers: headers,
            #fields: fields,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> postJson(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postJson,
          [url],
          {
            #headers: headers,
            #body: body,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> putJson(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putJson,
          [url],
          {
            #headers: headers,
            #body: body,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> deleteJson(
    Uri? url, {
    Map<String, String>? headers,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteJson,
          [url],
          {
            #headers: headers,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {
            #headers: headers,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {
              #headers: headers,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);
  @override
  _i5.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #headers: headers,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #headers: headers,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);
  @override
  _i5.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);
  @override
  _i5.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);
  @override
  _i5.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);
  @override
  _i5.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i7.Encoding? encoding,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response>);
  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {
            #headers: headers,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<_i8.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
    _i6.CancellationToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {
            #headers: headers,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i5.Future<_i8.Uint8List>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SearchRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRemoteSource extends _i1.Mock
    implements _i9.SearchRemoteSource {
  MockSearchRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Single<_i10.SearchResult> search(
    String? term,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            term,
            page,
          ],
        ),
        returnValue: _FakeSingle_1<_i10.SearchResult>(
          this,
          Invocation.method(
            #search,
            [
              term,
              page,
            ],
          ),
        ),
      ) as _i3.Single<_i10.SearchResult>);
}

/// A class which mocks [ColorRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockColorRemoteSource extends _i1.Mock implements _i11.ColorRemoteSource {
  MockColorRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Single<_i12.BuiltMap<String, _i13.Color>> getColors() =>
      (super.noSuchMethod(
        Invocation.method(
          #getColors,
          [],
        ),
        returnValue: _FakeSingle_1<_i12.BuiltMap<String, _i13.Color>>(
          this,
          Invocation.method(
            #getColors,
            [],
          ),
        ),
      ) as _i3.Single<_i12.BuiltMap<String, _i13.Color>>);
}
