include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/src/generated/*.dart"
    - "lib/generated/*.dart"
linter:
  rules:
    - prefer_final_locals