name: flutter_github_search_rx_redux
description: Flutter github search using rx_redux
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter_disposebag: ^1.0.0
  url_launcher: ^5.5.1
  rx_redux: ^2.1.0
  loading_indicator: ^1.2.0
  flutter_provider: ^1.1.1
  rxdart:
    git:
      url: 'https://github.com/ReactiveX/rxdart.git'
      ref: 'master'
  http: ^0.12.2
  built_value: ^7.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  mockito: ^4.1.2
  pedantic: ^1.9.0
  built_value_generator: ^7.1.0
  build_runner: ^1.10.2
  test:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icons8-github-96.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
