name: flutter_github_search_rx_redux
description: Flutter github search using rx_redux
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter_bloc_pattern: ^2.3.0
  flutter_disposebag: ^1.1.0
  rx_redux: ^2.5.0
  flutter_provider: ^2.1.0
  rxdart_ext: ^0.2.6
  did_change_dependencies: ^1.0.0

  built_collection: ^5.1.1
  rxdart: ^0.27.5
  http: ^0.13.4
  built_value: ^8.4.0
  url_launcher: ^6.1.5
  loading_indicator: ^3.1.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  mockito: ^5.2.0
  pedantic: ^1.11.1
  built_value_generator: ^8.4.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons8-github-96.png
