name: flutter_github_search_rx_redux
description: Flutter github search using rx_redux
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_bloc_pattern: ^2.0.0
  flutter_disposebag: ^1.1.0-nullsafety.1
  rx_redux: ^2.2.0-nullsafety.2
  flutter_provider: ^2.0.0
  rxdart_ext: ^0.0.1

  built_collection: ^5.0.0
  rxdart: ^0.26.0
  http: ^0.13.0
  built_value: ^8.0.3
  url_launcher: ^6.0.2
  loading_indicator: ^1.2.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dependency_overrides:
  loading_indicator:
    git:
      url: https://github.com/Mayb3Nots/loading_indicator.git
      ref: master

dev_dependencies:
  mockito: ^5.0.2
  pedantic: ^1.11.0
  built_value_generator: ^8.0.3
  build_runner: ^1.12.2
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons8-github-96.png
